$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
en: flujo de trabajo_dispatch

trabajos:
  si-Windows-else:
    se ejecuta en: macos-latest
    pasos:
      - nombre: condición 1
        si: corredor.os == 'Windows'
        run: echo "El sistema operativo del ejecutor es $env:RUNNER_OS."
      - nombre: condición 2
        si: corredor.os! = 'Windows'
        run: echo "The operating system on the runner is not Windows, it's $RUNNER_OS,"
        
        
